/*
 * Catálogo base de droguería: productos habituales con nombre, presentación y
 * categoría, pero SIN precio. Sirve de punto de partida para cargar el
 * inventario rápido: solo falta poner el precio (pantalla "Precios") y, si se
 * quiere, escanear el código de barras real.
 *
 * Formato: [clave de categoría, nombre con presentación, código de barras opcional].
 * Los productos marcados "(Rx)" requieren fórmula médica para su venta.
 */
(function (global) {
  'use strict';

  var CATEGORIAS = [
    { clave: 'med', nombre: 'Medicamentos' },
    { clave: 'analg', nombre: 'Analgésicos y antiinflamatorios', padre: 'med' },
    { clave: 'gripa', nombre: 'Antigripales', padre: 'med' },
    { clave: 'alerg', nombre: 'Antialérgicos', padre: 'med' },
    { clave: 'digest', nombre: 'Digestivos', padre: 'med' },
    { clave: 'antib', nombre: 'Antibióticos y antiinfecciosos', padre: 'med' },
    { clave: 'cardio', nombre: 'Cardiovascular y diabetes', padre: 'med' },
    { clave: 'derma', nombre: 'Dermatológicos', padre: 'med' },
    { clave: 'oft', nombre: 'Oftálmicos y óticos', padre: 'med' },
    { clave: 'mujer', nombre: 'Salud femenina y anticonceptivos', padre: 'med' },
    { clave: 'vit', nombre: 'Vitaminas y suplementos' },
    { clave: 'personal', nombre: 'Cuidado personal' },
    { clave: 'oral', nombre: 'Higiene oral', padre: 'personal' },
    { clave: 'piel', nombre: 'Cuidado de la piel', padre: 'personal' },
    { clave: 'cabello', nombre: 'Cabello', padre: 'personal' },
    { clave: 'desod', nombre: 'Desodorantes y afeitada', padre: 'personal' },
    { clave: 'intima', nombre: 'Higiene femenina', padre: 'personal' },
    { clave: 'maqui', nombre: 'Maquillaje y uñas', padre: 'personal' },
    { clave: 'sexual', nombre: 'Salud sexual' },
    { clave: 'aux', nombre: 'Primeros auxilios' },
    { clave: 'bebe', nombre: 'Bebé y maternidad' },
    { clave: 'mayor', nombre: 'Adulto mayor e incontinencia' },
    { clave: 'varios', nombre: 'Bebidas y misceláneos' }
  ];

  var PRODUCTOS = [
    // Analgésicos y antiinflamatorios
    ['analg', 'Dolex 500 mg x 10 tabletas'],
    ['analg', 'Dolex Forte x 10 tabletas'],
    ['analg', 'Dolex Niños 2+ jarabe x 90 ml'],
    ['analg', 'Dolex Niños 7+ x 20 tabletas masticables'],
    ['analg', 'Acetaminofén 500 mg x 100 tabletas'],
    ['analg', 'Acetaminofén jarabe 150 mg/5 ml x 90 ml'],
    ['analg', 'Acetaminofén gotas 100 mg/ml x 30 ml'],
    ['analg', 'Advil 200 mg x 10 tabletas'],
    ['analg', 'Advil Max 400 mg x 10 cápsulas'],
    ['analg', 'Advil Niños suspensión x 60 ml'],
    ['analg', 'Ibuprofeno 400 mg x 50 tabletas'],
    ['analg', 'Ibuprofeno 800 mg x 10 tabletas'],
    ['analg', 'Ibuprofeno suspensión 100 mg/5 ml x 60 ml'],
    ['analg', 'Naproxeno 500 mg x 10 tabletas'],
    ['analg', 'Apronax 550 mg x 10 tabletas'],
    ['analg', 'Diclofenaco 50 mg x 10 tabletas'],
    ['analg', 'Diclofenaco 75 mg ampolla x 3 ml (Rx)'],
    ['analg', 'Voltarén Emulgel 1% x 50 g'],
    ['analg', 'Aspirina 500 mg x 10 tabletas'],
    ['analg', 'Aspirina Efervescente x 10 tabletas'],
    ['analg', 'Ácido acetilsalicílico 100 mg x 30 tabletas'],
    ['analg', 'Noxpirin x 10 tabletas'],
    ['analg', 'Buscapina x 10 grageas'],
    ['analg', 'Buscapina Compositum x 10 grageas'],
    ['analg', 'Buscapina Fem x 10 tabletas'],
    ['analg', 'Dolofen x 10 tabletas'],
    ['analg', 'Meloxicam 15 mg x 10 tabletas'],
    ['analg', 'Nimesulida 100 mg x 10 tabletas'],
    ['analg', 'Ketorolaco 10 mg x 10 tabletas'],
    ['analg', 'Tramadol 50 mg x 10 cápsulas (Rx)'],
    ['analg', 'Metocarbamol 750 mg x 10 tabletas'],
    ['analg', 'Dolo-Neurobión x 10 tabletas'],
    ['analg', 'Mentol Chino pomada x 10 g'],
    ['analg', 'Bengay crema x 60 g'],
    ['analg', 'Parches térmicos para dolor x 2 unidades'],
    // Antigripales
    ['gripa', 'Dolex Gripa x 12 tabletas'],
    ['gripa', 'Dolex Gripa Noche x 12 tabletas'],
    ['gripa', 'Noxpirin Plus x 10 sobres'],
    ['gripa', 'Noraver Gripa x 12 cápsulas'],
    ['gripa', 'Noraver Garganta x 12 pastillas'],
    ['gripa', 'Advil Gripa x 10 tabletas'],
    ['gripa', 'Dristan Ultra x 12 cápsulas'],
    ['gripa', 'Winadeine F x 10 tabletas'],
    ['gripa', 'Bisolvón jarabe x 120 ml'],
    ['gripa', 'Ambroxol jarabe 30 mg/5 ml x 120 ml'],
    ['gripa', 'Acetilcisteína 600 mg x 10 sobres'],
    ['gripa', 'Loratadina + Fenilefrina jarabe x 60 ml'],
    ['gripa', 'Jarabe Tosil x 120 ml'],
    ['gripa', 'Vick VapoRub x 50 g'],
    ['gripa', 'Vick Pastillas x 12 unidades'],
    ['gripa', 'Halls x 9 pastillas'],
    ['gripa', 'Isodine garganta spray x 30 ml'],
    ['gripa', 'Suero nasal solución salina x 30 ml'],
    ['gripa', 'Oximetazolina gotas nasales x 15 ml'],
    // Antialérgicos
    ['alerg', 'Loratadina 10 mg x 100 tabletas'],
    ['alerg', 'Loratadina jarabe 5 mg/5 ml x 100 ml'],
    ['alerg', 'Cetirizina 10 mg x 10 tabletas'],
    ['alerg', 'Cetirizina jarabe x 60 ml'],
    ['alerg', 'Clarityne 10 mg x 10 tabletas'],
    ['alerg', 'Desloratadina 5 mg x 10 tabletas'],
    ['alerg', 'Fexofenadina 180 mg x 10 tabletas'],
    ['alerg', 'Clorfeniramina 4 mg x 20 tabletas'],
    ['alerg', 'Hidroxicina 25 mg x 20 tabletas (Rx)'],
    ['alerg', 'Prednisolona 5 mg x 20 tabletas (Rx)'],
    // Digestivos
    ['digest', 'Omeprazol 20 mg x 30 cápsulas'],
    ['digest', 'Esomeprazol 40 mg x 14 tabletas'],
    ['digest', 'Ranitidina 150 mg x 10 tabletas'],
    ['digest', 'Sal de Frutas Lua x 5 sobres'],
    ['digest', 'Alka-Seltzer x 12 tabletas'],
    ['digest', 'Milanta suspensión x 180 ml'],
    ['digest', 'Mylanta Plus x 10 tabletas masticables'],
    ['digest', 'Gaviscon suspensión x 150 ml'],
    ['digest', 'Hidróxido de magnesio (Leche de magnesia) x 120 ml'],
    ['digest', 'Bonfiest Plus x 2 tabletas'],
    ['digest', 'Mareol x 10 tabletas'],
    ['digest', 'Dimenhidrinato 50 mg x 10 tabletas'],
    ['digest', 'Metoclopramida 10 mg x 10 tabletas'],
    ['digest', 'Loperamida 2 mg x 6 tabletas'],
    ['digest', 'Pedialyte 45 x 500 ml'],
    ['digest', 'Suero oral Electrolit x 625 ml'],
    ['digest', 'Bisacodilo 5 mg x 20 tabletas'],
    ['digest', 'Fibra natural (psyllium) x 300 g'],
    ['digest', 'Simeticona gotas x 15 ml'],
    ['digest', 'Albendazol 400 mg x 1 tableta'],
    ['digest', 'Albendazol suspensión x 20 ml'],
    ['digest', 'Mebendazol 100 mg x 6 tabletas'],
    ['digest', 'Nitazoxanida 500 mg x 6 tabletas'],
    ['digest', 'Lactobacilos probióticos x 10 sobres'],
    // Antibióticos y antiinfecciosos
    ['antib', 'Amoxicilina 500 mg x 50 cápsulas (Rx)'],
    ['antib', 'Amoxicilina suspensión 250 mg/5 ml x 100 ml (Rx)'],
    ['antib', 'Cefalexina 500 mg x 10 cápsulas (Rx)'],
    ['antib', 'Azitromicina 500 mg x 3 tabletas (Rx)'],
    ['antib', 'Ciprofloxacina 500 mg x 10 tabletas (Rx)'],
    ['antib', 'Trimetoprim sulfametoxazol x 10 tabletas (Rx)'],
    ['antib', 'Metronidazol 500 mg x 10 tabletas (Rx)'],
    ['antib', 'Nitrofurantoína 100 mg x 40 cápsulas (Rx)'],
    ['antib', 'Clotrimazol crema 1% x 20 g'],
    ['antib', 'Fluconazol 150 mg x 1 cápsula'],
    ['antib', 'Aciclovir crema 5% x 5 g'],
    ['antib', 'Ivermectina gotas 0,6% x 5 ml (Rx)'],
    // Cardiovascular y diabetes
    ['cardio', 'Losartán 50 mg x 30 tabletas (Rx)'],
    ['cardio', 'Enalapril 20 mg x 30 tabletas (Rx)'],
    ['cardio', 'Amlodipino 5 mg x 30 tabletas (Rx)'],
    ['cardio', 'Hidroclorotiazida 25 mg x 30 tabletas (Rx)'],
    ['cardio', 'Metoprolol 50 mg x 30 tabletas (Rx)'],
    ['cardio', 'Atorvastatina 20 mg x 30 tabletas (Rx)'],
    ['cardio', 'Metformina 850 mg x 30 tabletas (Rx)'],
    ['cardio', 'Glibenclamida 5 mg x 30 tabletas (Rx)'],
    ['cardio', 'Tiras para glucómetro x 50 unidades'],
    ['cardio', 'Lancetas x 100 unidades'],
    ['cardio', 'Glucómetro'],
    ['cardio', 'Tensiómetro digital de brazo'],
    // Dermatológicos
    ['derma', 'Betametasona crema 0,05% x 40 g'],
    ['derma', 'Hidrocortisona crema 1% x 15 g'],
    ['derma', 'Clotrimazol + Betametasona crema x 20 g'],
    ['derma', 'Crema antipañalitis (óxido de zinc) x 60 g'],
    ['derma', 'Sulfadiazina de plata crema x 30 g'],
    ['derma', 'Gel de aloe vera x 120 ml'],
    ['derma', 'Crema cicatrizante x 30 g'],
    ['derma', 'Talco antimicótico para pies x 120 g'],
    ['derma', 'Permetrina loción 5% x 60 ml'],
    ['derma', 'Repelente de insectos spray x 120 ml'],
    // Oftálmicos y óticos
    ['oft', 'Lágrimas artificiales x 15 ml'],
    ['oft', 'Colirio descongestionante x 15 ml'],
    ['oft', 'Solución para lentes de contacto x 360 ml'],
    ['oft', 'Gotas para oídos x 10 ml'],
    // Salud femenina y anticonceptivos
    ['mujer', 'Píldora anticonceptiva x 21 tabletas (Rx)'],
    ['mujer', 'Píldora de emergencia x 1 tableta'],
    ['mujer', 'Inyección anticonceptiva mensual x 1 ampolla (Rx)'],
    ['mujer', 'Prueba de embarazo x 1 unidad'],
    ['mujer', 'Óvulos vaginales clotrimazol x 6 (Rx)'],
    ['mujer', 'Ácido fólico 1 mg x 30 tabletas'],
    // Vitaminas y suplementos
    ['vit', 'Vitamina C 1 g efervescente x 10 tabletas'],
    ['vit', 'Redoxon efervescente x 10 tabletas'],
    ['vit', 'Complejo B x 30 tabletas'],
    ['vit', 'Complejo B ampolla x 2 ml (Rx)'],
    ['vit', 'Vitamina E 400 UI x 30 cápsulas'],
    ['vit', 'Vitamina D3 1000 UI x 30 cápsulas'],
    ['vit', 'Sulfato ferroso 300 mg x 30 tabletas'],
    ['vit', 'Calcio + Vitamina D x 30 tabletas'],
    ['vit', 'Magnesio x 30 tabletas'],
    ['vit', 'Omega 3 x 30 cápsulas'],
    ['vit', 'Multivitamínico adulto x 30 tabletas'],
    ['vit', 'Centrum x 30 tabletas'],
    ['vit', 'Pediasure vainilla x 400 g'],
    ['vit', 'Ensure vainilla x 400 g'],
    ['vit', 'Emulsión de Scott tradicional x 180 ml'],
    ['vit', 'Colágeno hidrolizado x 300 g'],
    ['vit', 'Tarrito Rojo x 360 ml'],
    // Higiene oral
    ['oral', 'Crema dental Colgate Triple Acción x 75 ml'],
    ['oral', 'Crema dental Colgate Total 12 x 75 ml'],
    ['oral', 'Crema dental Sensodyne x 90 g'],
    ['oral', 'Crema dental infantil x 50 g'],
    ['oral', 'Cepillo dental adulto medio'],
    ['oral', 'Cepillo dental infantil'],
    ['oral', 'Enjuague bucal x 500 ml'],
    ['oral', 'Seda dental x 50 m'],
    ['oral', 'Adhesivo para prótesis dental x 40 g'],
    // Cuidado de la piel
    ['piel', 'Crema humectante corporal x 400 ml'],
    ['piel', 'Crema de manos x 100 ml'],
    ['piel', 'Protector solar FPS 50 x 60 ml'],
    ['piel', 'Protector solar infantil FPS 50 x 120 ml'],
    ['piel', 'Vaselina pura x 100 g'],
    ['piel', 'Crema Nivea lata x 150 ml'],
    ['piel', 'Jabón antibacterial x 3 barras'],
    ['piel', 'Jabón líquido antibacterial x 400 ml'],
    ['piel', 'Gel antibacterial x 500 ml'],
    ['piel', 'Toallitas desmaquillantes x 25'],
    ['piel', 'Bálsamo labial'],
    ['piel', 'Crema para peinar x 300 ml'],
    // Cabello
    ['cabello', 'Shampoo x 400 ml'],
    ['cabello', 'Acondicionador x 400 ml'],
    ['cabello', 'Shampoo anticaspa x 375 ml'],
    ['cabello', 'Shampoo infantil x 200 ml'],
    ['cabello', 'Loción antipiojos x 120 ml'],
    ['cabello', 'Gel fijador x 250 g'],
    ['cabello', 'Tinte para cabello'],
    // Desodorantes y afeitada
    ['desod', 'Desodorante roll-on x 50 ml'],
    ['desod', 'Desodorante en barra x 45 g'],
    ['desod', 'Desodorante en aerosol x 150 ml'],
    ['desod', 'Talco para pies x 120 g'],
    ['desod', 'Máquina de afeitar desechable x 2'],
    ['desod', 'Espuma de afeitar x 200 ml'],
    ['desod', 'Loción para después de afeitar x 100 ml'],
    // Higiene femenina
    ['intima', 'Toallas higiénicas normales x 10'],
    ['intima', 'Toallas higiénicas nocturnas x 8'],
    ['intima', 'Protectores diarios x 15'],
    ['intima', 'Tampones regulares x 10'],
    ['intima', 'Jabón íntimo x 200 ml'],
    ['intima', 'Copa menstrual'],
    // Maquillaje y uñas (vitrina "MAQUILLAJE" de la droguería). Los esmaltes se
    // registran por marca; cada tono tiene su propio código de barras, así que
    // conviene crear un producto por tono al escanearlo (Compras o Ventas).
    ['maqui', 'Esmalte Masglo tradicional x 13,5 ml (tono surtido)'],
    ['maqui', 'Esmalte Masglo escarchado x 13,5 ml (tono surtido)'],
    ['maqui', 'Esmalte Admiss (tono surtido)'],
    ['maqui', 'Base tratamiento Nutri Uñas con biotina y ajo'],
    ['maqui', 'Removedor de esmalte Lander tradicional'],
    ['maqui', 'Removedor de esmalte pequeño'],
    ['maqui', 'Removedor de cutícula Mariposa'],
    ['maqui', 'Pegante para uñas'],
    ['maqui', 'Tratamiento para uñas mini'],
    ['maqui', 'Polvo compacto Nailen'],
    ['maqui', 'Base de maquillaje líquida'],
    ['maqui', 'Lápiz delineador'],
    ['maqui', 'Labial en barra'],
    ['maqui', 'Brillo labial'],
    ['maqui', 'Bálsamo labial ChapStick'],
    ['maqui', 'Vaselina perfumada tarro pequeño'],
    ['maqui', 'Crema en tarro tapa roja'],
    // Salud sexual
    ['sexual', 'Preservativos x 3 unidades'],
    ['sexual', 'Preservativos x 12 unidades'],
    ['sexual', 'Lubricante íntimo x 60 ml'],
    // Primeros auxilios
    ['aux', 'Algodón x 50 g'],
    ['aux', 'Algodón x 500 g'],
    ['aux', 'Gasa estéril 7,5 x 7,5 cm x 10 sobres'],
    ['aux', 'Esparadrapo de tela 1 pulgada'],
    ['aux', 'Micropore 1 pulgada'],
    ['aux', 'Venda elástica 3 pulgadas'],
    ['aux', 'Venda elástica 5 pulgadas'],
    ['aux', 'Curitas redondas x 100 unidades'],
    ['aux', 'Agua oxigenada x 120 ml'],
    ['aux', 'Isodine solución x 120 ml'],
    ['aux', 'Clorhexidina solución x 120 ml'],
    ['aux', 'Alcohol antiséptico 70% x 700 ml'],
    ['aux', 'Alcohol glicerinado x 250 ml'],
    ['aux', 'Guantes de látex x 100 unidades'],
    ['aux', 'Guantes de nitrilo x 100 unidades'],
    ['aux', 'Guantes de látex Eterna x 100 unidades'],
    ['aux', 'Guantes Inverfarma x 100 unidades'],
    ['aux', 'Guantes de nitrilo Handel x 100 unidades'],
    ['aux', 'Guantes de nitrilo UltraSafe x 100 unidades'],
    ['aux', 'Guantes de nitrilo negros Precision Care x 100 unidades'],
    ['aux', 'Guantes de nitrilo negros x 100 unidades'],
    ['aux', 'Guantes desechables de nitrilo x 50 unidades'],
    ['aux', 'Jeringa 3 ml con aguja'],
    ['aux', 'Jeringa 5 ml con aguja'],
    ['aux', 'Jeringa 10 ml con aguja'],
    ['aux', 'Termómetro digital'],
    ['aux', 'Oxímetro de pulso'],
    ['aux', 'Bolsa para agua caliente'],
    ['aux', 'Inmovilizador de muñeca'],
    ['aux', 'Tapabocas N95'],
    ['aux', 'Suero fisiológico 0,9% x 100 ml'],
    ['aux', 'Solución Hartmann x 500 ml (Rx)'],
    // Bebé y maternidad
    ['bebe', 'Pañales etapa 1 x 30 unidades'],
    ['bebe', 'Pañales etapa 2 x 30 unidades'],
    ['bebe', 'Pañales etapa 4 x 30 unidades'],
    ['bebe', 'Pañales etapa 5 x 30 unidades'],
    ['bebe', 'Pañitos húmedos x 100 unidades'],
    ['bebe', 'Pañitos húmedos x 50 unidades'],
    ['bebe', 'Crema antipañalitis x 110 g'],
    ['bebe', 'Aceite para bebé x 200 ml'],
    ['bebe', 'Jabón para bebé x 110 g'],
    ['bebe', 'Talco para bebé x 200 g'],
    ['bebe', 'Tetero x 9 onzas'],
    ['bebe', 'Chupo de entretención'],
    ['bebe', 'Leche de fórmula etapa 1 x 400 g'],
    ['bebe', 'Leche de fórmula etapa 2 x 400 g'],
    ['bebe', 'Leche de fórmula etapa 3 x 800 g'],
    ['bebe', 'Compota de frutas x 113 g'],
    ['bebe', 'Copitos (hisopos) x 100 unidades'],
    ['bebe', 'Extractor de leche manual'],
    ['bebe', 'Protectores de lactancia x 30'],
    // Adulto mayor e incontinencia
    ['mayor', 'Pañal adulto talla M x 10 unidades'],
    ['mayor', 'Pañal adulto talla L x 10 unidades'],
    ['mayor', 'Pañal adulto talla XL x 10 unidades'],
    ['mayor', 'Toallas para incontinencia x 10'],
    ['mayor', 'Pañitos húmedos adulto x 48'],
    ['mayor', 'Crema protectora para adulto x 200 g'],
    ['mayor', 'Pastillero semanal'],
    ['mayor', 'Bastón de aluminio'],
    ['mayor', 'Medias de compresión'],
    // Bebidas y misceláneos
    ['varios', 'Agua mineral x 600 ml'],
    ['varios', 'Gatorade x 500 ml'],
    // Nevera de bebidas (códigos leídos de la foto; los marcados "por confirmar"
    // conviene verificarlos escaneando el producto).
    ['varios', 'Gatorade rojo x 500 ml', '7702192422051'],
    ['varios', 'Jugo Hit botella roja x 500 ml (sabor por confirmar)', '7707133052670'],
    ['varios', 'Jugo Hit botella naranja x 500 ml (sabor por confirmar)', '7707133062471'],
    ['varios', 'Jugo Hit Frutas Tropicales caja x 200 ml', '7707133025919'],
    ['varios', 'Jugo Hit Mango caja x 200 ml'],
    ['varios', 'Agua Cristal x 300 ml', '7702090073065'],
    ['varios', 'Agua Cristal x 600 ml', '7702090022711'],
    ['varios', 'Agua Cristal x 1 L'],
    ['varios', 'Suero oral sobre x 1'],
    ['varios', 'Bebida hidratante infantil x 500 ml'],
    ['varios', 'Galletas integrales x 6 paquetes'],
    ['varios', 'Chicles sin azúcar'],
    ['varios', 'Bolsa de compra'],
    ['varios', 'Pilas AA x 2'],
    ['varios', 'Pilas AAA x 2'],
    ['varios', 'Pila de reloj CR2032']
  ];

  global.CATALOGO_BASE = { categorias: CATEGORIAS, productos: PRODUCTOS };
})(window);
